"""added columnn for pitch

Revision ID: 6a011ba56c78
Revises: e27369e14878
Create Date: 2018-09-13 15:17:15.666514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a011ba56c78'
down_revision = 'e27369e14878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('body', sa.String(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'body')
    # ### end Alembic commands ###
